"""SQLAlchemy ORM models.

All timestamps are UTC.  UUIDs are generated by Postgres (gen_random_uuid()).
"""
import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.sql import func


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    hashed_pw: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    services: Mapped[list["Service"]] = relationship("Service", back_populates="user", cascade="all, delete-orphan")


class Service(Base):
    __tablename__ = "services"
    __table_args__ = (UniqueConstraint("user_id", "name", name="uq_service_user_name"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    method: Mapped[str] = mapped_column(String(10), nullable=False, server_default="GET")
    interval_secs: Mapped[int] = mapped_column(Integer, nullable=False, server_default="60")
    timeout_ms: Mapped[int] = mapped_column(Integer, nullable=False, server_default="5000")
    expected_status: Mapped[int] = mapped_column(Integer, nullable=False, server_default="200")
    headers: Mapped[dict] = mapped_column(JSONB, nullable=False, server_default="{}")
    body: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    user: Mapped["User"] = relationship("User", back_populates="services")
    check_results: Mapped[list["CheckResult"]] = relationship(
        "CheckResult", back_populates="service", cascade="all, delete-orphan"
    )
    status: Mapped[Optional["ServiceStatus"]] = relationship(
        "ServiceStatus", back_populates="service", uselist=False, cascade="all, delete-orphan"
    )
    incidents: Mapped[list["Incident"]] = relationship(
        "Incident", back_populates="service", cascade="all, delete-orphan"
    )
    alert_rules: Mapped[list["AlertRule"]] = relationship(
        "AlertRule", back_populates="service", cascade="all, delete-orphan"
    )


class CheckResult(Base):
    __tablename__ = "check_results"
    __table_args__ = (
        Index("idx_cr_service_time", "service_id", "checked_at"),
        Index("idx_cr_node_time", "checker_node_id", "checked_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="CASCADE"), nullable=False
    )
    checker_node_id: Mapped[str] = mapped_column(String(128), nullable=False)
    checked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    status: Mapped[str] = mapped_column(String(20), nullable=False)  # up|down|timeout|error
    status_code: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    response_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    raw_headers: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    idempotency_key: Mapped[str] = mapped_column(String(256), unique=True, nullable=False)

    service: Mapped["Service"] = relationship("Service", back_populates="check_results")


class ServiceStatus(Base):
    __tablename__ = "service_status"

    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="CASCADE"), primary_key=True
    )
    current_status: Mapped[str] = mapped_column(String(20), nullable=False, server_default="unknown")
    since: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    last_checked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    uptime_7d: Mapped[Optional[float]] = mapped_column(Numeric(5, 2), nullable=True)
    p50_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    p99_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)

    service: Mapped["Service"] = relationship("Service", back_populates="status")


class Incident(Base):
    __tablename__ = "incidents"
    __table_args__ = (
        Index("idx_incidents_service", "service_id", "started_at"),
        Index(
            "idx_incidents_open",
            "service_id",
            postgresql_where="resolved_at IS NULL",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="CASCADE"), nullable=False
    )
    started_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    resolved_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    trigger_reason: Mapped[str] = mapped_column(String(512), nullable=False)
    ai_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    ai_generated_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    alert_sent: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")

    service: Mapped["Service"] = relationship("Service", back_populates="incidents")
    context_chunks: Mapped[list["IncidentContext"]] = relationship(
        "IncidentContext", back_populates="incident", cascade="all, delete-orphan"
    )


class IncidentContext(Base):
    __tablename__ = "incident_context"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("incidents.id", ondelete="CASCADE"), nullable=False
    )
    chunk_text: Mapped[str] = mapped_column(Text, nullable=False)

    incident: Mapped["Incident"] = relationship("Incident", back_populates="context_chunks")


class AlertRule(Base):
    __tablename__ = "alert_rules"
    __table_args__ = (UniqueConstraint("service_id", "channel", "destination", name="uq_alert_rule"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    service_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("services.id", ondelete="CASCADE"), nullable=False
    )
    channel: Mapped[str] = mapped_column(String(32), nullable=False)  # email|slack|discord
    destination: Mapped[str] = mapped_column(Text, nullable=False)
    on_incident: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
    on_resolve: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")

    service: Mapped["Service"] = relationship("Service", back_populates="alert_rules")
